<a href="https://colab.research.google.com/github/anshatwork-007/Study-of-Pandas-in-Python/blob/main/Experiment_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: Ansh Yadav
# Branch: ENTC
# Batch: 2025-29
# Experiment 9

## Title: Study of Pandas in Python

In [ ]:
import pandas as pd
s = pd.Series([1, 3, 5, 6, 8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [ ]:
# Create DataFrame

data = {"Name":["A","B","C"],
        "Marks":[85,90,95]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     95

In [ ]:
# Find structure of DataFrame
df.shape

(3, 2)

In [ ]:
df.size

6

In [ ]:
df.ndim

2

In [ ]:
# Display Column names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [ ]:
# Check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [ ]:
## Access individual colums
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [ ]:
df["Marks"]

0    85
1    90
2    95
Name: Marks, dtype: int64

In [ ]:
# Access Specicfic row
df.loc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [ ]:
# Add a new column

df["Grade"] = ["First Class", "Distinction", "Second Class"]

In [ ]:
df

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     95  Second Class

In [ ]:
# Update data in dataframe
# Change marks of A to 88
df.loc[0,"Marks"] = 88

In [ ]:
df

  Name  Marks
0    A     88
1    B     90
2    C     95

In [ ]:
# Delete a column
df.drop("Grade", axis=1, inplace=True)
df

  Name  Marks
0    A     88
1    B     90
2    C     95

In [ ]:
# Perform basic Statistical Analysis
min1 = df["Marks"].min()
min1

88

In [ ]:
max1 = df["Marks"].max()
max1

95

In [ ]:
mean1 = df["Marks"].mean()
mean1

np.float64(91.0)

In [ ]:
# Apply condition(Filtering)
# Diplay students scoring more than 80

df[df["Marks"] > 80]

  Name  Marks
0    A     88
1    B     90
2    C     95